# Generated by Django 4.2.11 on 2024-03-27 22:58

from django.db import migrations
import say_core.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', say_core.users.models.UserManager()),
            ],
        ),
    ]
