# Generated by Django 4.2.11 on 2024-03-27 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_oid', models.BigIntegerField(db_index=True, unique=True)),
                ('is_default', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegramuserprofile_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram User Profile',
                'db_table': 'telegrambot_telegramuserprofile',
            },
        ),
        migrations.AddConstraint(
            model_name='telegramuserprofilemodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='only_one_default_telegram_profile_per_user'),
        ),
    ]
