# Generated by Django 4.2.11 on 2024-04-03 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_oid', models.BigIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'db_table': 'telegrambot_telegramchannel',
            },
        ),
        migrations.CreateModel(
            name='TGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_oid', models.BigIntegerField(unique=True)),
                ('type', models.CharField(choices=[('group', 'telegram simple group'), ('supergroup', 'telegram super group')], max_length=31)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Telegram Group',
                'db_table': 'telegrambot_tgroup',
            },
        ),
        migrations.CreateModel(
            name='TGroupRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tgroupregister_set', to='telegram_bot.tgroupmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tgroupregister_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Group Register',
                'db_table': 'telegrambot_tgroupregister',
            },
        ),
        migrations.CreateModel(
            name='TChannelRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tchannel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tchannelregister_set', to='telegram_bot.tchannelmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tchannelregister_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='tgroupregistermodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tgroup',), name='only_one_active_tgrouprequest_per_tgroup'),
        ),
    ]
