# Generated by Django 4.2.11 on 2024-03-27 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogging', '0002_wppostmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wppostmodel',
            options={'verbose_name': 'WordPress Post'},
        ),
        migrations.RemoveField(
            model_name='wpsitemodel',
            name='owner',
        ),
        migrations.AlterModelTable(
            name='wppostmodel',
            table='blogging_wppost',
        ),
        migrations.CreateModel(
            name='WPRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_fsm.FSMField(choices=[('wait_for_code_entrance', 'waiting for code to be used')], max_length=50)),
                ('code', models.CharField(max_length=127)),
                ('code_generated_at', models.DateTimeField()),
                ('code_used_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wpregister_set', to='blogging.wpsitemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wpregister_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WordPress Register',
                'db_table': 'blogging_wpregister',
            },
        ),
    ]
