# Generated by Django 4.2.11 on 2024-03-27 22:58

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('blogging', '0003_alter_wppostmodel_options_remove_wpsitemodel_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpregistermodel',
            name='apikey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wpregister_set', to='rest_framework_api_key.apikey'),
        ),
        migrations.AlterField(
            model_name='wpregistermodel',
            name='status',
            field=django_fsm.FSMField(choices=[('wait_for_code_entrance', 'waiting for code to be used'), ('registered', 'registered')], max_length=50),
        ),
    ]
